Update Addd

diff --git a/Addd b/Addd
--- a/Addd
+++ b/Addd
@@ -71,7 +71,14 @@ read -p " Password SSH : " Pass
 read -p " Limit IP     : " iplimit
 read -p " Limit Quota  : " Quota
 read -p " Expired Days : " masaaktif
-#limitip
+# --- VALIDASI INPUT ---
+if [[ -z "$Login" || -z "$Pass" ]]; then
+    echo -e "${RED}Error: Username & Password tidak boleh kosong!${NC}"
+    exit 1
+fi
+
+# --- 1. PROSES SSH ---
+# Limit IP SSH
 if [[ $iplimit -gt 0 ]]; then
 mkdir -p /etc/kyt/limit/ssh/ip
 echo -e "$iplimit" > /etc/kyt/limit/ssh/ip/$Login
@@ -88,6 +95,7 @@ tgl2=$(date +"%d")
 bln2=$(date +"%b")
 thn2=$(date +"%Y")
 tnggl="$tgl2 $bln2, $thn2"
+exp_date_iso=$(date -d "$masaaktif days" +"%Y-%m-%d") # Format untuk JSON
 useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $Login
 expi="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
 echo -e "$Pass\n$Pass\n"|passwd $Login &> /dev/null
